In [6]:
import numpy as np #import numpy
x = np.array([[55, 6], [5, 61], [4, 7]]) #inisialisasi matrix berukuran 2x3
print(x) #tampilkan matrix
print(x.size) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua

import torch
import tensorflow as tf
x = torch.tensor([[55, 6], [5, 61], [4, 7]]) #inisialisasi matrix berukuran 2x3 menggunaakan torch
print(x) #tampilkan matrix
print(x.shape) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua
x = tf.Variable([[55, 6], [5, 61], [4, 7]]) #inisialisasi matrix berukuran 2x3 menggunaakan tensorflow
print(x) #tampilkan matrix
print(x.shape) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua


[[55  6]
 [ 5 61]
 [ 4  7]]
6
[55  5  4]
[ 5 61]
tensor([[55,  6],
        [ 5, 61],
        [ 4,  7]])
torch.Size([3, 2])
tensor([55,  5,  4])
tensor([ 5, 61])
<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[55,  6],
       [ 5, 61],
       [ 4,  7]], dtype=int32)>
(3, 2)
tf.Tensor([55  5  4], shape=(3,), dtype=int32)
tf.Tensor([ 5 61], shape=(2,), dtype=int32)
