In [11]:
import numpy as np #import numpy
x = np.array([5, 55, 61]) #inialisasi vektor
print(len(x)) #tampilkan panjang vektor
print(x.shape) #tampilkan bentuk vektor
print(type(x)) #tampilkan tipe data vektor
print(type(x[0])) #tampilkan tipe data dari elemen pertama

x_t = x.T # tranpose x dan massukan dalam x_t
print(x_t) #tampilkan tranpose x
print(x_t.shape) #tampilkan bentuk tranpose x
y = np.array([61, 55, 5]) #inisialisasi variabel y
y_t = y.T #tranpose x dan masukkan ke y_t
print(y_t) #tampilkan tranpose y
print(len(y_t)) #tampilakan ukuran dari y_t

import torch #import torch dari library
import tensorflow as tf #torch dari library
x_pt = torch.tensor([5, 55, 61]) #inisialisasi vektor menggunakan torch
print(x_pt) # tampilkan x_pt
x_pt_t = x_pt.T #tranpose x_pt dan masukkan ke x_pt_t
print(x_pt_t) #tampilkan x_pt_t
print(len(x_pt_t)) #tampilkan ukuran x_pt_t
y_pt = torch.tensor([61, 5, 55]) #inisialisasi vektor menggunakan torch
print(y_pt) # tampilkan y_pt
print(len(y_pt)) #tampilkan ukuran y_pt

x_pt = tf.Variable([5, 55, 61]) #inisialisasi vektor menggunakan tf
print(x_pt) # tampilkan x_pt
x_pt_t = tf.transpose(x_pt) #tranpose x_pt dan masukkan ke x_pt_t
print(x_pt_t) #tampilkan x_pt_t
print(len(x_pt_t)) #tampilkan ukuran x_pt_t
y_pt = tf.Variable([61, 5, 55]) #inisialisasi vektor menggunakan tf
print(y_pt) # tampilkan y_pt
print(y_pt.dtype) #tampilkan ukuran y_pt

3
(3,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[ 5 55 61]
(3,)
[61 55  5]
3
tensor([ 5, 55, 61])
tensor([ 5, 55, 61])
3
tensor([61,  5, 55])
3
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 55, 61], dtype=int32)>
tf.Tensor([ 5 55 61], shape=(3,), dtype=int32)
3
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([61,  5, 55], dtype=int32)>
<dtype: 'int32'>
